.TH ERIC4_PLUGINUNINSTALL 1 "January 31, 2010"
.SH NAME
eric5_pluginuninstall \- Plugin uninstallation utility for eric5
.SH SYNOPSIS
.B eric5_pluginuninstall
.RI [ options ] " files" ...
.SH DESCRIPTION
This manual page documents briefly the
.B eric5_pluginuninstall
program. This manual page was written for the Debian 
distribution because the original program does not have a manual page.
Instead, it has documentation provided in HTML format.

.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-\-version
Show version of program.
.TP
.B \-\-nokde
Don't use KDE widgets
.SH SEE ALSO
.BR eric5 (1),
.BR eric5_api (1),
.BR eric5_compare (1),
.BR eric5_configure (1),
.BR eric5_diff (1),    
.BR eric5_doc (1),
.BR eric5_editor (1),    
.BR eric5_helpviewer (1),
.BR eric5_iconeditor (1),
.BR eric5_plugininstall (1),  
.BR eric5_pluginrepository (1), 
.BR eric5_qregexp (1),
.BR eric5_re (1),
.BR eric5_sqlbrowser (1),        
.BR eric5_tray (1),        
.BR eric5_trpreviewer (1),
.BR eric5_uipreviewer (1),
.BR eric5_unittest (1),
.BR eric5_webbrowser (1)
.SH AUTHOR
eric5_pluginuninstall was written by Detlev Offenbach.
.PP
This manual page was written by Gudjon I. Gudjonsson <gudjon@gudjon.org>,
for the Debian project (but may be used by others).
